services:
  - type: web
    name: sign-language-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
      - key: GROQ_API_KEY
        sync: false
